version: '1.0'

services:
  app:
    image: queekquaak/vnc-rm-app:1.0  # Название собранного Docker-образа
    container_name: vnc-rm-app        # Фиксированное имя контейнера
    restart: unless-stopped           # Автоперезапуск при падении
    ports:
      - "5000:5000"                # Пробрасываем порт (host:container)
#     Основные настройки сервера.
#     Рекомендуется использовать .env !
    environment:
     - FRONTEND_PORT=${FRONTEND_PORT}           # Порт работы app (должен совпадать с ports)
     - API_SERVER_ADDR=${API_SERVER_ADDR}
     - API_AUTH_TOKEN=${API_AUTH_TOKEN}
     - VIEW_ONLY_PASS=${VIEW_ONLY_PASS}
     - TZ=Europe/Moscow            # Часовой пояс
     - PYTHONUNBUFFERED=1          # Для немедленного вывода логов Python
#     Опциональные настройки
#     - VNC_COMPRESSION=9           # Степень сжатия изображения (0-9)
#     - VNC_TILE_QUALITY=1          # Глубина цвета в режиме просмотра
#     - VNC_FULLSCREEN_QUALITY=5    # Глубина цвета в режиме управления
    volumes:
      - ./vnc-rm-app/data:/app/data
# volumes: # Для постоянного хранения (если нужно)
#   app-data:
